# Generated by Django 5.0.5 on 2024-05-06 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idCliente', models.CharField(max_length=100)),
                ('nome', models.CharField(max_length=45)),
                ('cpf', models.CharField(max_length=11)),
                ('endereco', models.CharField(max_length=45)),
                ('telefone', models.CharField(max_length=11)),
                ('dataNascimento', models.DateField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
